name: Validate YAML against JSON Schema
description: Composite action that validates a given YAML file against a JSON schema

author: "CDQ AG"
branding:
  icon: 'check-square'
  color: 'green'

inputs:
  file:
    description: YAML file to validate
    required: true

  schema:
    description: 'JSON schema to validate against. If not provided, the action will try to extract it from the YAML file using the comment "# yaml-language-server: $schema=URL"'
    default: ""

  schema-dialect:
    description: 'JSON schema dialect. Only used if not provided in the schema. Value must have format: "https://json-schema.org/[path]/schema"'
    default: ""

runs:
  using: 'composite'
  steps:
    - name: Get schema URI
      id: get-schema-uri
      shell: bash
      env:
        TARGET_FILE: ${{ inputs.file }}
        SCHEMA_INPUT: ${{ inputs.schema }}
      run: ${{ github.action_path }}/src/get-schema-uri.sh

    - name: Fetch schema
      id: fetch-schema
      shell: bash
      env:
        SCHEMA_URI: ${{ steps.get-schema-uri.outputs.uri }}
        SCHEMA_PATH: ${{ runner.temp }}/schema.json
      run: ${{ github.action_path }}/src/fetch-schema.sh

    - name: Check schema dialect
      id: check-schema-dialect
      shell: bash
      env:
        SCHEMA_PATH: ${{ steps.fetch-schema.outputs.path }}
        SCHEMA_DIALECT_INPUT: ${{ inputs.schema-dialect }}
      run: ${{ github.action_path }}/src/check-schema-dialect.sh

    - name: Install the JSON Schema CLI
      uses: sourcemeta/jsonschema@v11.8.3

    - name: Validate YAML
      shell: bash
      env:
        YAML_FILE: ${{ inputs.file }}
        SCHEMA_PATH: ${{ steps.fetch-schema.outputs.path }}
        SCHEMA_DIALECT: ${{ steps.check-schema-dialect.outputs.dialect }}
        RESULTS_PATH: ${{ runner.temp }}/results.json
      run: ${{ github.action_path }}/src/validate-yaml.sh
